# Generated by Django 3.0.7 on 2021-10-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20211017_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
