# Generated by Django 3.0.7 on 2021-10-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=200, verbose_name='cantidad')),
                ('fecha_compra', models.DateField(verbose_name='fecha compra ')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['cantidad'],
            },
        ),
        migrations.CreateModel(
            name='Faltante',
            fields=[
                ('id_faltante', models.AutoField(primary_key=True, serialize=False)),
                ('faltante', models.CharField(max_length=200, verbose_name='faltante')),
            ],
            options={
                'verbose_name': 'Faltente',
                'verbose_name_plural': 'Faltantes',
                'ordering': ['faltante'],
            },
        ),
    ]
