# Generated by Django 3.0.7 on 2021-10-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0002_compra_faltante'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='id_repuesto',
            field=models.ManyToManyField(to='repuestos.Repuesto'),
        ),
    ]
