# Generated by Django 3.0.7 on 2021-10-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0006_auto_20211007_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='faltante',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
