# Generated by Django 3.0.7 on 2020-09-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motovehiculo',
            fields=[
                ('id_motovehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(default='', max_length=100, verbose_name='Patente')),
                ('tipo_motovehiculo', models.CharField(default='', max_length=200, verbose_name='Tipo del motovehiculo')),
                ('cilindrada', models.IntegerField()),
                ('trasmision', models.CharField(default='', max_length=200, verbose_name='Trasmision del motovehiculo')),
                ('color', models.CharField(default='', max_length=100, verbose_name='Color del motovehicuio')),
                ('Marca', models.CharField(default='', max_length=100, verbose_name='Marca del motovehiculo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
