# Generated by Django 3.0.7 on 2021-10-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20210930_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motovehiculo',
            old_name='cliente_id',
            new_name='id_cliente',
        ),
    ]
