# Generated by Django 3.0.7 on 2021-10-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20210930_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motovehiculo',
            name='id_cliente',
        ),
    ]
