# Generated by Django 3.0.7 on 2021-10-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_motovehiculo_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motovehiculo',
            name='id_cliente',
        ),
    ]
