# Generated by Django 3.0.7 on 2021-10-01 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_motovehiculo_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='motovehiculo',
            name='cliente_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
    ]
