# Generated by Django 3.0.7 on 2020-09-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('detalles', models.CharField(default='', max_length=200, verbose_name='Detalles')),
                ('tipo_servicio', models.CharField(default='', max_length=220, verbose_name='Tipo de servicio')),
                ('Precio', models.IntegerField(default=0, verbose_name='Precio del servicio')),
                ('Observaciones', models.CharField(default='', max_length=300, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_trabajo', models.CharField(max_length=300, verbose_name='Tipo de trabajo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_finalizacion', models.DateField(verbose_name='Fecha de finalizacion')),
                ('detalle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Detalle de trabajo')),
                ('estado', models.CharField(max_length=50, verbose_name='Estadp de trabajo')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['estado'],
            },
        ),
    ]
