# Generated by Django 3.0.7 on 2021-10-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20211024_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_turno',
            field=models.DateTimeField(verbose_name='Fecha del turno'),
        ),
    ]
