# Generated by Django 3.0.7 on 2022-05-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_auto_20211024_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
