# Generated by Django 3.0.7 on 2021-10-01 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor'),
        ),
    ]
