# Generated by Django 3.0.7 on 2021-10-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20211001_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_proveedor',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.categoria'),
        ),
    ]
