# Generated by Django 3.0.7 on 2021-10-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_auto_20211001_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='id_categoria',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_categoria',
            field=models.ManyToManyField(null=True, to='proveedores.categoria'),
        ),
    ]
