# Generated by Django 3.0.7 on 2021-10-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_auto_20211002_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='id_categoria',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.categoria'),
        ),
    ]
